# Generated by Django 4.2.4 on 2023-09-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
