# Generated by Django 4.2.4 on 2023-09-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_superhero_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
