# Generated by Django 4.2.4 on 2023-09-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_alter_superhero_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='heroClass',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
