# Generated by Django 4.2.4 on 2023-09-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_alter_superhero_heroclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='heroClass',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
