# Generated by Django 4.2.4 on 2023-11-14 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=100)),
                ('hero', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hero.superhero')),
            ],
        ),
    ]
