# Generated by Django 4.2.4 on 2023-10-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_investigator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('identity', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('strength', models.CharField(default='', max_length=100)),
                ('weakness', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='image', max_length=100)),
            ],
        ),
    ]
