# Generated by Django 4.2.4 on 2023-10-30 03:47

from django.db import migrations, models
import django.db.models.deletion
import hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_superhero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hero.models.get_upload),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=100)),
                ('hero', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hero.superhero')),
            ],
        ),
    ]
