alerts:
- disabled: true
  rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: db
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
features:
- buildpack-stack=ubuntu-22
name: proj09-tlee
region: nyc
services:
- build_command: pip install -r requirements.txt
  environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: DATABASE_ENGINE
    scope: RUN_AND_BUILD_TIME
    value: django.db.backends.sqlite3
  - key: DATABASE_NAME
    scope: RUN_AND_BUILD_TIME
    value: config/service.db
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  - key: DJANGO_SUPERUSER_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: SuperUser@email.com
  - key: DJANGO_SUPERUSER_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: admin
  - key: DJANGO_SUPERUSER_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:j/UmtYG4O1Ce/QszcLIkEBcO86955jfs:MinMlM01XcRLw7ZH7ZQERisTCsbBzl5LkhBMWbU=]
  github:
    branch: production
    deploy_on_push: true
    repo: TheMaiTAI/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: service
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    python manage.py loaddata hero_database.json
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Student/09
static_sites:
- environment_slug: html
  github:
    branch: production
    deploy_on_push: true
    repo: TheMaiTAI/PythonWebApps
  name: static
  routes:
  - path: /static
  source_dir: Student/09/static
