# Generated by Django 4.2.4 on 2023-10-14 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hero Name', max_length=100)),
                ('identity', models.CharField(default='Civilian Name', max_length=100)),
                ('description', models.TextField(default='Description')),
                ('strength', models.CharField(default='Strength', max_length=100)),
                ('weakness', models.CharField(default='Weakness', max_length=100)),
                ('image', models.CharField(default='Image', max_length=100)),
                ('slug', models.SlugField(default='hero-name', unique=True)),
                ('heroClass', models.CharField(default='heroClass', max_length=200, null=True)),
            ],
            options={
                'db_table': 'hero_database',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='heronews.author')),
            ],
        ),
    ]
