# Generated by Django 4.2.4 on 2023-10-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heronews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
