# Generated by Django 4.2.4 on 2023-10-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heronews', '0002_remove_author_user_delete_article_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Article Title', max_length=100)),
                ('body', models.TextField(default='Article Body')),
            ],
        ),
    ]
